CREATE DATABASE IF NOT EXISTS `symfony`;
CREATE DATABASE IF NOT EXISTS `symfony_test`;
CREATE USER 'symfony'@'%' IDENTIFIED BY '!ChangeMe!';
GRANT ALL PRIVILEGES ON *.* TO 'symfony'@'%' WITH GRANT OPTION;
